name: Issue Labeler
on: issue_comment

jobs:
  add_ascend_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.comment.body.toLowerCase();
            if (body.includes('ascend')) {
              await github.rest.issues.addLables({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['ascend']
              });
            }